name: thessariakos
description: "App for thessaloniki ring road drivers/passengers to express there opinion."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  http: ^1.2.1
  latlong2: ^0.9.1
  flutter_map: ^7.0.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  device_info: ^2.0.3
  platform_device_id: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
#    - assets/icons/